export const metadata = {
  title: 'TrailBlaze',
  description: 'Generated by TrailBlaze',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
